spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/music-platform
    username: postgres
    password: g12nokona
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

minio:
  url:
    http://127.0.0.1:9000
  bucket:
    name:
      tinkoff-music
  access:
    key:
      zhurkin
    secret:
      g12nokona

