spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/music-platform
    username: postgres
    password: 2108cret
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

minio:
  url:
    http://127.0.0.1:9000
  bucket:
    name:
      tinkoff-music-platform
  access:
    key:
      minioadmin
    secret:
        minioadmin

